name: mindwm-dev1 cluster

on:
  push:
    branches: [ "master" ]

jobs:
  redeploy_cluster:

    runs-on: [self-hosted, prod]

    steps:
    - uses: actions/checkout@v4

    - name: Redeploy the k3s cluster
      run: make mindwm_lifecycle
