name: allure-test-report

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Load fake results
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          token: ${{ secrets.MINDWM_TOKEN }}
          repository: 'mindwm/sandbox'
          ref: master
          path: sandbox

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: sandbox/artifact_dir
    
  upload-report:
    needs: ci
    uses: ./.github/workflows/allure-report-reusable.yml
    with:
      artifact_name: 'test-results'
    secrets:
      MINDWM_TOKEN: ${{ secrets.MINDWM_TOKEN }}
