name: ci badge

on:
  workflow_call:
    inputs:
      junit_total: 
        required: true
        type: string
      junit_passed:
        required: true
        type: string
      junit_skipped:
        required: true
        type: string
      junit_failed:
        required: true
        type: string
    secrets:
      MINDWM_TOKEN:
        required: true

    # outputs:
    #   test_result:
    #     description: "Test result"
    #     value: ${{ jobs.allure_report.outputs.test_result }}
    #   test_result_url:
    #     description: "Test result url"
    #     value: ${{ jobs.allure_report.outputs.test_result_url }}
    #   test_result_icon:
    #     description: "Test result icon"
    #     value: ${{ jobs.allure_report.outputs.test_result_icon }}
    #
env:
  badge_path: badges/${{ github.repository }}/${{ github.job }}/${{ github.ref_name }}
  badge_file: badges/${{ github.repository }}/${{ github.job }}/${{ github.ref_name }}/badge.svg

jobs:
  ci_badge:
    runs-on: ubuntu-latest
    # outputs:
    #   test_result: ${{ steps.allure.outputs.test_result }}
    #   test_result_url: ${{ steps.allure.outputs.report_url }}
    #   test_result_icon: ${{ steps.allure.outputs.test_result_icon }}
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ${{ inputs.artifact_name }}
      #     path: artifact_dir

      - name: Load report history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          token: ${{ secrets.MINDWM_TOKEN }}
          repository: 'mindwm/mindwm.github.io'
          ref: badges
          path: gh-pages

      - name: Create destination directory
        env:
          BADGE_PATH: ${{ env.badge_path }}
        run: mkdir -p gh-pages/"${BADGE_PATH}"

      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v2.0.3
        id: badge
        with:
          label: 'Allure report'
          status: "${{ inputs.junit_total }} Total/${{ inputs.junit_passed }} Passed/${{ inputs.junit_skipped }} Skipped/${{ inputs.junit_failed }} ${{ inputs.junit_failed }}"
          color: 'blue,555,daf'
          path: ${{ env.badge_file }}

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: badge
          path: ${{ env.badge_file }}
          if-no-files-found: error


      - name: Upload badge file
        id: update_mindwm_github_io
        run: |
          cd gh-pages/
          git add ${{ env.badge_file }}
          git config --global user.email "metacoma"
          git config --global user.name "ryabin.ss@gmail.com"
          git commit -m 'Upload badge' || echo "nothing to commit"
          git push origin badges
