name: Run linode instance

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      artifact_state_name: 
        required: true
        type: string
    secrets:
      LINODE_TOKEN:
        required: true
      ROOT_PASSWORD:
        required: true

jobs:
  linode_instance:
    runs-on: ubuntu-latest
    steps:
      - name: Debug artifact name
        run: |
          echo "Artifact name: ${{ inputs.artifact_name }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_name }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: terraform init
        working-directory: ${{ inputs.artifact_name }}
        run: terraform init

      - name: terraform plan
        working-directory: ${{ inputs.artifact_name }}
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_TOKEN }}
          TF_VAR_root_password: ${{ secrets.ROOT_PASSWORD }}
          TF_VAR_node_name: "mindwm-ci-${{ github.run_number }}-${{ github.run_attempt }}"
        run: terraform plan

      - name: terraform apply
        working-directory: ${{ inputs.artifact_name }}
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_TOKEN }}
          TF_VAR_root_password: ${{ secrets.ROOT_PASSWORD }}
          TF_VAR_node_name: "mindwm-ci-${{ github.run_number }}-${{ github.run_attempt }}"
        run: terraform apply -auto-approve

      - name: Upload terraform manifest results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_state_name }}
          path: ${{ inputs.artifact_name }}
