name: Test result

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      test_result:
        required: true
        type: string

jobs:
  test_result:
    runs-on: ubuntu-latest
    steps:
      - name: test result
        run: |
          echo "Test result was: ${{ inputs.test_result }}"

