name: Sync code
on:
  repository_dispatch:
    types: [mindwm_gitops_updated]
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Deployment environment'
  #       required: true
  #       default: 'staging'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Clone mindwm/mindwm-gitops repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'mindwm'
          repository: 'mindwm-gitops'

      - name: before
        run: |
          ls -ltrh mindwm-gitops.yaml
          ls -ltrh mindwm-gitops


      - name: Run KCL and generate mindwm-gitops.yaml
        uses: docker://kcllang/kcl:v0.9.7
        with:
          args: /bin/sh -c "(cd mindwm-gitops && kcl run > /mindwm-gitops-new.yaml); rm -rf mindwm-gitops"

      - name: after
        run: |
          ls -ltrh mindwm-gitops.yaml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
