name: Sync code
on:
  # schedule:
  #   - cron: '0/15 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Clone mindwm/mindwm-gitops repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'mindwm'
          repository: 'mindwm-gitops'
      - name: ls
        run: |
          find
