name: Sync code
on:
  # schedule:
  #   - cron: '0/15 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Clone mindwm/mindwm-gitops repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'mindwm'
          repository: 'mindwm-gitops'

      - name: Run KCL and generate mindwm-gitops.yaml
        uses: docker://kcllang/kcl:v0.9.7
        with:
          args: /bin/sh -c "(cd mindwm-gitops && kcl run > /mindwm-gitops.yaml); rm -rf mindwm-gitops"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: kcl run
      #   container: kcllang/kcl:v0.9.7
      #   run: |
      #     cd mindwm-gitops
      #     kcl run | tee ../test.yaml 
      #     ls -ltr ../test.yaml
