name: Sync code
on:
  repository_dispatch:
    types: [mindwm_gitops_updated]
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Deployment environment'
  #       required: true
  #       default: 'staging'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Clone mindwm/mindwm-gitops repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'mindwm'
          repository: 'mindwm-gitops'

      - name: before
        run: |
          md5sum mindwm-gitops.yaml
          ls -ltrh mindwm-gitops


      - name: Run KCL and generate mindwm-gitops.yaml
        uses: docker://kcllang/kcl:v0.11.0
        with:
          args: |
            /bin/sh -c "
              (cd mindwm-gitops && kcl run -q) > mindwm-gitops.yaml;
              cp -vr mindwm-gitops/tests/ tests/ 
              cp -vr mindwm-gitops/.github/workflows github-workflows
              cp -vr mindwm-gitops/Makefile .
              cp -vr mindwm-gitops/config.k .
              cp -vr mindwm-gitops/kcl.mod .
              rm -rf mindwm-gitops
            "
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
